#pragma once

/**
 * RuleStrategy — bounded, user-configurable entry/exit rule evaluator
 * (Phase 8.2).
 *
 * A strategy is a RuleSpec: a list of entry conditions and a list of exit
 * conditions, each AND-ed together. Conditions compare a whitelisted
 * indicator against a numeric value or another indicator. Long-only:
 * all-entry-true while flat emits LONG; all-exit-true while long emits EXIT.
 * An empty exit list means hold to the end (buy-and-hold when paired with an
 * always-true entry).
 *
 * The spec file is a flat line format generated by the Python API layer,
 * which owns rich validation (Pydantic). The parser here is intentionally
 * strict and minimal — one canonical schema, two consumers (ADR-046):
 *
 *   version: 2
 *   name: ma_cross
 *   direction: short              # version 2 only; default long
 *   entry: SMA:10 crosses_above SMA:50
 *   entry: RSI:14 < 30
 *   exit: SMA:10 crosses_below SMA:50
 *
 * Operand tokens: PRICE | SMA:p | EMA:p | RSI:p | HIGH_N:p | LOW_N:p
 * Operators:      < | > | crosses_above | crosses_below
 * RHS:            a number, or another operand token.
 *
 * Versions: 1 = long-only (Phase 8). 2 adds the optional `direction` key
 * (ADR-049); a `direction` line under version 1 is a parse error so old
 * consumers never mis-run a short spec as long.
 *
 * Direction semantics: single-sided position state machine in both modes —
 * entry conditions open the position (LONG or SHORT signal), exit
 * conditions close it (EXIT). Short specs require the engine to enable
 * allow_short (main.cpp wires this from the parsed spec).
 *
 * Hard caps: at most 8 conditions per side; periods in [2, 250]; at least
 * one entry condition.
 */

#include "strategy/Strategy.hpp"
#include "events/SignalEvent.hpp"

#include <deque>
#include <map>
#include <string>
#include <vector>

enum class RuleIndicator { PRICE, SMA, EMA, RSI, HIGH_N, LOW_N };
enum class RuleOp { LT, GT, CROSS_ABOVE, CROSS_BELOW };
enum class RuleDirection { LONG, SHORT };

struct RuleOperand {
    RuleIndicator indicator = RuleIndicator::PRICE;
    int period = 0;                    ///< 0 for PRICE; [2,250] otherwise
};

struct RuleCondition {
    RuleOperand lhs;
    RuleOp op = RuleOp::GT;
    bool rhsIsValue = true;
    double value = 0.0;                ///< used when rhsIsValue
    RuleOperand rhs;                   ///< used when !rhsIsValue
};

struct RuleSpec {
    int version = 1;
    std::string name;
    RuleDirection direction = RuleDirection::LONG;
    std::vector<RuleCondition> entry;
    std::vector<RuleCondition> exit;

    static constexpr int MAX_CONDITIONS_PER_SIDE = 8;
    static constexpr int MIN_PERIOD = 2;
    static constexpr int MAX_PERIOD = 250;

    /// Parse and validate a spec file. Throws std::invalid_argument with a
    /// human-readable message on any violation.
    static RuleSpec loadFromFile(const std::string& path);

    /// Longest lookback any condition needs before it can evaluate.
    int warmupBars() const;
};

class RuleStrategy : public Strategy {
public:
    explicit RuleStrategy(RuleSpec spec);

    void onMarketEvent(const MarketEvent& event, EventQueue& queue) override;

private:
    RuleSpec spec_;
    int warmup_;
    std::deque<double> closes_;        ///< rolling window, capped at warmup_+1
    bool inPosition_ = false;

    // Indicator values for the previous bar, keyed by "IND:period" — needed
    // for cross conditions.
    std::map<std::string, double> prevValues_;
    bool hasPrev_ = false;

    double indicatorValue(const RuleOperand& op) const;
    bool conditionsMet(const std::vector<RuleCondition>& conds,
                       const std::map<std::string, double>& current) const;
    std::map<std::string, double> computeAll() const;
};
