/**
 * Cross-validation of indicator math against the shared fixture
 * (tests/fixtures/indicator_crossval.csv, Phase 9.1, ADR-048).
 *
 * The fixture is generated by scripts/gen_indicator_fixture.py with plain
 * reference formulas; the Python side pins technicalIndicators.py against
 * the same file (tests/test_indicator_crossval.py). If either
 * implementation drifts from its documented contract, exactly one of the
 * two suites fails and points at the divergence.
 */
#include <deque>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "strategy/Indicators.hpp"

#ifndef FIXTURE_DIR
#error "FIXTURE_DIR must be defined by CMake"
#endif

namespace {

struct FixtureRow {
    double close;
    bool hasSma = false,  hasEma = false,  hasRsi = false,  hasChannel = false;
    double sma = 0, ema = 0, rsi = 0, high = 0, low = 0;
};

std::vector<FixtureRow> loadFixture() {
    const std::string path =
        std::string(FIXTURE_DIR) + "/indicator_crossval.csv";
    std::ifstream file(path);
    EXPECT_TRUE(file.is_open()) << "cannot open fixture: " << path;

    std::vector<FixtureRow> rows;
    std::string line;
    std::getline(file, line);  // header
    while (std::getline(file, line)) {
        std::stringstream ss(line);
        std::string cell;
        FixtureRow row{};
        std::getline(ss, cell, ',');
        row.close = std::stod(cell);
        if (std::getline(ss, cell, ',') && !cell.empty()) {
            row.sma = std::stod(cell); row.hasSma = true;
        }
        if (std::getline(ss, cell, ',') && !cell.empty()) {
            row.ema = std::stod(cell); row.hasEma = true;
        }
        if (std::getline(ss, cell, ',') && !cell.empty()) {
            row.rsi = std::stod(cell); row.hasRsi = true;
        }
        if (std::getline(ss, cell, ',') && !cell.empty()) {
            row.high = std::stod(cell);
            std::getline(ss, cell, ',');
            row.low = std::stod(cell);
            row.hasChannel = true;
        }
        rows.push_back(row);
    }
    return rows;
}

}  // namespace

TEST(IndicatorCrossValidation, AllRowsMatchTheSharedFixture) {
    const auto rows = loadFixture();
    ASSERT_EQ(rows.size(), 60u) << "fixture regenerated with a different size?";

    std::deque<double> prefix;
    int checked = 0;
    for (std::size_t i = 0; i < rows.size(); ++i) {
        prefix.push_back(rows[i].close);

        if (rows[i].hasSma) {
            EXPECT_NEAR(indicators::sma(prefix, 10), rows[i].sma, 1e-6)
                << "SMA mismatch at row " << i;
            ++checked;
        }
        if (rows[i].hasEma) {
            EXPECT_NEAR(indicators::emaSeeded(prefix, 10), rows[i].ema, 1e-6)
                << "EMA mismatch at row " << i;
        }
        if (rows[i].hasRsi) {
            EXPECT_NEAR(indicators::rsi(prefix, 14), rows[i].rsi, 1e-6)
                << "RSI mismatch at row " << i;
        }
        if (rows[i].hasChannel) {
            EXPECT_NEAR(indicators::highestBefore(prefix, 5), rows[i].high, 1e-9)
                << "HIGH_N mismatch at row " << i;
            EXPECT_NEAR(indicators::lowestBefore(prefix, 5), rows[i].low, 1e-9)
                << "LOW_N mismatch at row " << i;
        }
    }
    EXPECT_GT(checked, 40) << "fixture unexpectedly sparse";
}

TEST(IndicatorCrossValidation, RsiSaturatesAtHundredOnAllGains) {
    // The fixture's forced rally must exercise the loss==0 branch.
    const auto rows = loadFixture();
    bool sawSaturation = false;
    for (const auto& row : rows) {
        if (row.hasRsi && row.rsi == 100.0) sawSaturation = true;
    }
    EXPECT_TRUE(sawSaturation)
        << "no RSI=100 row — regenerate fixture with a >14-bar rally";
}
